avatar: https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/29ecc7afd2984de8b6115c86b52b0bec~tplv-k3u1fbpfcp-watermark.image # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://raw.githubusercontent.com/ch1ny/PictureCDN/master/others/f0d5cc34c6e5aa7.jpg
    width: 1280
    height: 720
favicon:
    href: https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/29ecc7afd2984de8b6115c86b52b0bec~tplv-k3u1fbpfcp-watermark.image # 网站图标
    type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 使用说明：https://hexo.kira.host/config/icon
iconlib: //at.alicdn.com/t/c/font_3846301_yjnjkz051y.css

cdn: # 这里可以修改站点使用的库的CDN
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js

beian: 赣ICP备******号 # 备案号（选填，此乃中国特色，不得不尝）

menu:
    回到首页:
        - /
        - icon-shouye
    文章归档: # 使用说明：https://docs.kira.com/article/archive
        - /archive.html
        - icon-guidangrenwu
    关于本人:
        - /about.html
        - icon-web__guanyuwomen

widgets:
    - social
    - category
    - tagcloud

maxTagcloud: 0 # 标签云组件显示的标签数量，0 表示不限制

social:
    知乎:
        - https://www.zhihu.com/people/mz-60-50
        - icon-zhihu-circle-fill
        - rgb(49, 174, 255)
        - rgba(49, 174, 255, .1)
    邮箱:
        - tsdfuw12@qq.com
        - icon-youxiang
        - rgb(231, 106, 141)
        - rgba(231, 106, 141, .15)

color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
    first: # 同时作为主题色
        r: 49
        g: 174
        b: 255
    second:
        r: 255
        g: 78
        b: 106
    third:
        r: 255
        g: 185
        b: 0
    fourth:
        r: 51
        g: 213
        b: 122
    fifth:
        r: 0
        g: 219
        b: 255
    sixth:
        r: 255
        g: 69
        b: 0
    seventh:
        r: 144
        g: 144
        b: 255

# 评论区
gitalk:
    active: true # 是否启用 gitalk
    admin: -your github username- # 拥有对该repo进行操作的 GitHub username
    owner: -your github username- # 持有该 repo 的 GitHub username
    repo: -issue repo name- # 存放评论的 issue 所在的 repo
    clientID: -id- # GitHub Client ID
    clientSecret: -key- # GitHub Client Secret
    title: '' # Gitalk Issue Title

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'
copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

# achive widget behavior
widgetAchive: #文章归档组件
    archive_type: 'year' #按月展示还是按年展示
    show_count: true #是否展示数量

widgetLink: #链接组件
    - title: <title>
      img: <img_path>
      link: <url>
    - title: <title>
      img: <img_path>
      link: <url>

# 自定义侧边栏尾部内容
sidebar: ''
